# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{delayed_form_observer}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Coroutine", "Tim Lowrimore", "John Dugan"]
  s.date = %q{2010-07-29}
  s.description = %q{Delayed Form Observer provides Rails with timed form observers that do not create race conditions.}
  s.email = %q{gems@coroutine.com}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    ".gitignore",
     ".specification",
     "MIT-LICENSE",
     "README",
     "Rakefile",
     "VERSION",
     "delayed_form_observer.gemspec",
     "generators/delayed_form_observer/delayed_form_observer_generator.rb",
     "generators/delayed_form_observer/templates/prototype_extension.js",
     "init.rb",
     "lib/delayed_form_observer.rb",
     "lib/delayed_form_observer/helpers.rb",
     "rails/init.rb",
     "test/delayed_form_observer/helpers_test.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/coroutine/delayed_form_observer}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Delayed Form Observer provides Rails with timed form observers that do not create race conditions.}
  s.test_files = [
    "test/delayed_form_observer/helpers_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<actionpack>, [">= 2.3.4"])
      s.add_development_dependency(%q<activesupport>, [">= 2.3.4"])
    else
      s.add_dependency(%q<actionpack>, [">= 2.3.4"])
      s.add_dependency(%q<activesupport>, [">= 2.3.4"])
    end
  else
    s.add_dependency(%q<actionpack>, [">= 2.3.4"])
    s.add_dependency(%q<activesupport>, [">= 2.3.4"])
  end
end

